swagger: "2.0"
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
host: localhost:8080
basePath: api
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/article/{articleId}:
        get:
            tags:
                - article
            summary: get article
            operationId: article#get
            parameters:
                - name: articleId
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ArticleGetResponseBody'
                        required:
                            - article
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ArticleGetArticleBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/article/{articleId}/delete:
        post:
            tags:
                - article
            summary: delete article
            operationId: article#delete
            parameters:
                - name: articleId
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ArticleDeleteArticleBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/article/{articleId}/favorite:
        post:
            tags:
                - article
            summary: favorite article
            operationId: article#favorite
            parameters:
                - name: articleId
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ArticleFavoriteResponseBody'
                        required:
                            - article
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ArticleFavoriteArticleBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/article/{articleId}/unfavorite:
        post:
            tags:
                - article
            summary: unfavorite article
            operationId: article#unfavorite
            parameters:
                - name: articleId
                  in: path
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ArticleUnfavoriteResponseBody'
                        required:
                            - article
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ArticleUnfavoriteArticleBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/article/{articleId}/update:
        post:
            tags:
                - article
            summary: update article
            operationId: article#update
            parameters:
                - name: articleId
                  in: path
                  required: true
                  type: string
                  format: uuid
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ArticleUpdateRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ArticleUpdateResponseBody'
                        required:
                            - article
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ArticleUpdateArticleBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/article/create:
        post:
            tags:
                - article
            summary: create article
            operationId: article#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ArticleCreateRequestBody'
                    required:
                        - title
                        - description
                        - body
                        - tagList
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ArticleCreateResponseBody'
                        required:
                            - article
            schemes:
                - http
    /api/articles:
        get:
            tags:
                - article
            summary: list article
            operationId: article#list
            parameters:
                - name: ListRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ArticleListRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ArticleListResponseBody'
                        required:
                            - articles
            schemes:
                - http
    /api/articles/feed:
        get:
            tags:
                - article
            summary: feed article
            operationId: article#feed
            parameters:
                - name: FeedRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ArticleFeedRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ArticleFeedResponseBody'
                        required:
                            - articles
            schemes:
                - http
    /api/profile/follow_user:
        post:
            tags:
                - profile
            summary: followUser profile
            operationId: profile#followUser
            parameters:
                - name: FollowUserRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileFollowUserRequestBody'
                    required:
                        - username
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProfileFollowUserResponseBody'
                        required:
                            - profile
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileFollowUserBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/profile/unfollow_user:
        post:
            tags:
                - profile
            summary: unfollowUser profile
            operationId: profile#unfollowUser
            parameters:
                - name: UnfollowUserRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileUnfollowUserRequestBody'
                    required:
                        - username
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProfileUnfollowUserResponseBody'
                        required:
                            - profile
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileUnfollowUserBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrent user
            operationId: user#getCurrent
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserGetCurrentResponseBody'
                        required:
                            - user
            schemes:
                - http
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserLoginRequestBody'
                    required:
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserLoginResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserLoginBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            parameters:
                - name: RegisterRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserRegisterRequestBody'
                    required:
                        - username
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserRegisterResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserRegisterBadRequest'
                        required:
                            - code
            schemes:
                - http
    /api/user/update:
        post:
            tags:
                - user
            summary: update user
            operationId: user#update
            parameters:
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserUpdateRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserUpdateResponseBody'
                        required:
                            - user
            schemes:
                - http
definitions:
    ArticleCreateRequestBody:
        title: ArticleCreateRequestBody
        type: object
        properties:
            body:
                type: string
                example: Eum eligendi.
            description:
                type: string
                example: Facere sed iste quis officiis ex ex.
            tagList:
                type: array
                items:
                    type: string
                    example: Aut molestiae dolor qui tenetur doloremque atque.
                example:
                    - Non voluptatem a aperiam ad quaerat id.
                    - Illum temporibus dignissimos id.
                    - Voluptas quia asperiores quasi non.
            title:
                type: string
                example: hym
                maxLength: 128
        example:
            body: Nostrum quidem et assumenda.
            description: Ut voluptatem libero dolorem.
            tagList:
                - Deleniti porro magni nulla recusandae.
                - Consequuntur sit provident veniam consequatur quia.
                - Eos cumque.
                - Non ullam aut esse amet.
            title: 4p6
        required:
            - title
            - description
            - body
            - tagList
    ArticleCreateResponseBody:
        title: ArticleCreateResponseBody
        type: object
        properties:
            article:
                $ref: '#/definitions/ArticleDetail'
        example:
            article:
                articleId: 702ce4ba-5930-428e-b06c-f0ac6b249188
                author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                body: Provident iste eum.
                createdAt: "2000-03-03T11:42:32Z"
                description: Occaecati quas quis excepturi.
                favorited: false
                favoritesCount: 16396543013077051002
                tagList:
                    - Ea provident voluptates laborum hic laborum error.
                    - Iure optio omnis et autem.
                    - Harum et neque minus eveniet vero.
                    - Tenetur dolorum quos sunt aut.
                title: Excepturi possimus molestiae laudantium libero veniam voluptatem.
                updatedAt: "2002-02-05T08:11:46Z"
        required:
            - article
    ArticleDeleteArticleBadRequest:
        title: ArticleDeleteArticleBadRequest
        type: object
        properties:
            code:
                type: string
                example: ForbiddenOperation
                enum:
                    - Unspecified
                    - ArticleNotFound
                    - ForbiddenOperation
        example:
            code: ForbiddenOperation
        required:
            - code
    ArticleDetail:
        title: ArticleDetail
        type: object
        properties:
            articleId:
                type: string
                example: 513f9648-16fa-4980-b1d9-2fc4165b37c9
                format: uuid
            author:
                $ref: '#/definitions/Profile'
            body:
                type: string
                example: Consequatur laboriosam.
            createdAt:
                type: string
                example: "2014-03-11T14:56:51Z"
                format: date-time
            description:
                type: string
                example: Expedita omnis nesciunt reiciendis voluptates.
            favorited:
                type: boolean
                example: false
            favoritesCount:
                type: integer
                example: 17091281289010325286
                format: int64
            tagList:
                type: array
                items:
                    type: string
                    example: Eum et praesentium quia maxime quia dolorem.
                example:
                    - Magni expedita sit.
                    - Expedita animi id ut.
            title:
                type: string
                example: Quibusdam aut hic repellat dolores.
            updatedAt:
                type: string
                example: "1976-12-31T00:54:28Z"
                format: date-time
        example:
            articleId: 324dd8a0-5f88-44a0-a59c-ea4e6771b8e5
            author:
                bio: Quas architecto voluptas.
                following: true
                image: Reiciendis ab voluptas adipisci non.
                username: Nostrum voluptate minima incidunt hic quis.
            body: Non non.
            createdAt: "1995-09-02T12:16:04Z"
            description: Autem ut sapiente architecto earum laboriosam officia.
            favorited: false
            favoritesCount: 13596011189779875243
            tagList:
                - Voluptas provident aspernatur et omnis minus.
                - Dolor voluptate assumenda qui.
                - Consequatur rerum rerum aut.
            title: Sint sed est.
            updatedAt: "1991-02-18T05:57:10Z"
        required:
            - articleId
            - title
            - description
            - body
            - tagList
            - createdAt
            - updatedAt
            - favorited
            - favoritesCount
            - author
    ArticleFavoriteArticleBadRequest:
        title: ArticleFavoriteArticleBadRequest
        type: object
        properties:
            code:
                type: string
                example: ArticleNotFound
                enum:
                    - Unspecified
                    - ArticleNotFound
        example:
            code: ArticleNotFound
        required:
            - code
    ArticleFavoriteResponseBody:
        title: ArticleFavoriteResponseBody
        type: object
        properties:
            article:
                $ref: '#/definitions/ArticleDetail'
        example:
            article:
                articleId: 702ce4ba-5930-428e-b06c-f0ac6b249188
                author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                body: Provident iste eum.
                createdAt: "2000-03-03T11:42:32Z"
                description: Occaecati quas quis excepturi.
                favorited: false
                favoritesCount: 16396543013077051002
                tagList:
                    - Ea provident voluptates laborum hic laborum error.
                    - Iure optio omnis et autem.
                    - Harum et neque minus eveniet vero.
                    - Tenetur dolorum quos sunt aut.
                title: Excepturi possimus molestiae laudantium libero veniam voluptatem.
                updatedAt: "2002-02-05T08:11:46Z"
        required:
            - article
    ArticleFeedRequestBody:
        title: ArticleFeedRequestBody
        type: object
        properties:
            limit:
                type: integer
                default: 20
                example: 900
                format: int32
                minimum: 1
                maximum: 1000
            offset:
                type: integer
                default: 0
                example: 2108602149
                format: int32
                minimum: 0
        example:
            limit: 193
            offset: 2050227907
    ArticleFeedResponseBody:
        title: ArticleFeedResponseBody
        type: object
        properties:
            articles:
                type: array
                items:
                    $ref: '#/definitions/ArticleSummary'
                example:
                    - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                      author:
                        bio: Quas architecto voluptas.
                        following: true
                        image: Reiciendis ab voluptas adipisci non.
                        username: Nostrum voluptate minima incidunt hic quis.
                      createdAt: "2014-08-01T11:05:33Z"
                      description: Ea mollitia facere ut inventore voluptatem.
                      favorited: true
                      favoritesCount: 14126625635488546158
                      tagList:
                        - Perferendis quo pariatur nulla velit doloribus.
                        - Ullam autem libero molestiae error.
                      title: Voluptas optio quia sint sequi ut.
                      updatedAt: "1976-02-29T20:46:09Z"
                    - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                      author:
                        bio: Quas architecto voluptas.
                        following: true
                        image: Reiciendis ab voluptas adipisci non.
                        username: Nostrum voluptate minima incidunt hic quis.
                      createdAt: "2014-08-01T11:05:33Z"
                      description: Ea mollitia facere ut inventore voluptatem.
                      favorited: true
                      favoritesCount: 14126625635488546158
                      tagList:
                        - Perferendis quo pariatur nulla velit doloribus.
                        - Ullam autem libero molestiae error.
                      title: Voluptas optio quia sint sequi ut.
                      updatedAt: "1976-02-29T20:46:09Z"
                    - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                      author:
                        bio: Quas architecto voluptas.
                        following: true
                        image: Reiciendis ab voluptas adipisci non.
                        username: Nostrum voluptate minima incidunt hic quis.
                      createdAt: "2014-08-01T11:05:33Z"
                      description: Ea mollitia facere ut inventore voluptatem.
                      favorited: true
                      favoritesCount: 14126625635488546158
                      tagList:
                        - Perferendis quo pariatur nulla velit doloribus.
                        - Ullam autem libero molestiae error.
                      title: Voluptas optio quia sint sequi ut.
                      updatedAt: "1976-02-29T20:46:09Z"
        example:
            articles:
                - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                  author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                  createdAt: "2014-08-01T11:05:33Z"
                  description: Ea mollitia facere ut inventore voluptatem.
                  favorited: true
                  favoritesCount: 14126625635488546158
                  tagList:
                    - Perferendis quo pariatur nulla velit doloribus.
                    - Ullam autem libero molestiae error.
                  title: Voluptas optio quia sint sequi ut.
                  updatedAt: "1976-02-29T20:46:09Z"
                - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                  author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                  createdAt: "2014-08-01T11:05:33Z"
                  description: Ea mollitia facere ut inventore voluptatem.
                  favorited: true
                  favoritesCount: 14126625635488546158
                  tagList:
                    - Perferendis quo pariatur nulla velit doloribus.
                    - Ullam autem libero molestiae error.
                  title: Voluptas optio quia sint sequi ut.
                  updatedAt: "1976-02-29T20:46:09Z"
        required:
            - articles
    ArticleGetArticleBadRequest:
        title: ArticleGetArticleBadRequest
        type: object
        properties:
            code:
                type: string
                example: Unspecified
                enum:
                    - Unspecified
                    - ArticleNotFound
        example:
            code: ArticleNotFound
        required:
            - code
    ArticleGetResponseBody:
        title: ArticleGetResponseBody
        type: object
        properties:
            article:
                $ref: '#/definitions/ArticleDetail'
        example:
            article:
                articleId: 702ce4ba-5930-428e-b06c-f0ac6b249188
                author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                body: Provident iste eum.
                createdAt: "2000-03-03T11:42:32Z"
                description: Occaecati quas quis excepturi.
                favorited: false
                favoritesCount: 16396543013077051002
                tagList:
                    - Ea provident voluptates laborum hic laborum error.
                    - Iure optio omnis et autem.
                    - Harum et neque minus eveniet vero.
                    - Tenetur dolorum quos sunt aut.
                title: Excepturi possimus molestiae laudantium libero veniam voluptatem.
                updatedAt: "2002-02-05T08:11:46Z"
        required:
            - article
    ArticleListRequestBody:
        title: ArticleListRequestBody
        type: object
        properties:
            author:
                type: string
                example: Provident nulla ut eum quos quis quo.
            favorited:
                type: string
                example: Expedita ea.
            limit:
                type: integer
                default: 20
                example: 730
                format: int32
                minimum: 1
                maximum: 1000
            offset:
                type: integer
                default: 0
                example: 1689014625
                format: int32
                minimum: 0
            tag:
                type: string
                example: Voluptas earum laboriosam officia est placeat qui.
        example:
            author: Iste rerum omnis officiis eveniet incidunt quia.
            favorited: Magnam ea et quia provident porro neque.
            limit: 615
            offset: 1535962071
            tag: Sed quam quisquam molestiae.
    ArticleListResponseBody:
        title: ArticleListResponseBody
        type: object
        properties:
            articles:
                type: array
                items:
                    $ref: '#/definitions/ArticleSummary'
                example:
                    - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                      author:
                        bio: Quas architecto voluptas.
                        following: true
                        image: Reiciendis ab voluptas adipisci non.
                        username: Nostrum voluptate minima incidunt hic quis.
                      createdAt: "2014-08-01T11:05:33Z"
                      description: Ea mollitia facere ut inventore voluptatem.
                      favorited: true
                      favoritesCount: 14126625635488546158
                      tagList:
                        - Perferendis quo pariatur nulla velit doloribus.
                        - Ullam autem libero molestiae error.
                      title: Voluptas optio quia sint sequi ut.
                      updatedAt: "1976-02-29T20:46:09Z"
                    - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                      author:
                        bio: Quas architecto voluptas.
                        following: true
                        image: Reiciendis ab voluptas adipisci non.
                        username: Nostrum voluptate minima incidunt hic quis.
                      createdAt: "2014-08-01T11:05:33Z"
                      description: Ea mollitia facere ut inventore voluptatem.
                      favorited: true
                      favoritesCount: 14126625635488546158
                      tagList:
                        - Perferendis quo pariatur nulla velit doloribus.
                        - Ullam autem libero molestiae error.
                      title: Voluptas optio quia sint sequi ut.
                      updatedAt: "1976-02-29T20:46:09Z"
                    - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                      author:
                        bio: Quas architecto voluptas.
                        following: true
                        image: Reiciendis ab voluptas adipisci non.
                        username: Nostrum voluptate minima incidunt hic quis.
                      createdAt: "2014-08-01T11:05:33Z"
                      description: Ea mollitia facere ut inventore voluptatem.
                      favorited: true
                      favoritesCount: 14126625635488546158
                      tagList:
                        - Perferendis quo pariatur nulla velit doloribus.
                        - Ullam autem libero molestiae error.
                      title: Voluptas optio quia sint sequi ut.
                      updatedAt: "1976-02-29T20:46:09Z"
        example:
            articles:
                - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                  author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                  createdAt: "2014-08-01T11:05:33Z"
                  description: Ea mollitia facere ut inventore voluptatem.
                  favorited: true
                  favoritesCount: 14126625635488546158
                  tagList:
                    - Perferendis quo pariatur nulla velit doloribus.
                    - Ullam autem libero molestiae error.
                  title: Voluptas optio quia sint sequi ut.
                  updatedAt: "1976-02-29T20:46:09Z"
                - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                  author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                  createdAt: "2014-08-01T11:05:33Z"
                  description: Ea mollitia facere ut inventore voluptatem.
                  favorited: true
                  favoritesCount: 14126625635488546158
                  tagList:
                    - Perferendis quo pariatur nulla velit doloribus.
                    - Ullam autem libero molestiae error.
                  title: Voluptas optio quia sint sequi ut.
                  updatedAt: "1976-02-29T20:46:09Z"
                - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                  author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                  createdAt: "2014-08-01T11:05:33Z"
                  description: Ea mollitia facere ut inventore voluptatem.
                  favorited: true
                  favoritesCount: 14126625635488546158
                  tagList:
                    - Perferendis quo pariatur nulla velit doloribus.
                    - Ullam autem libero molestiae error.
                  title: Voluptas optio quia sint sequi ut.
                  updatedAt: "1976-02-29T20:46:09Z"
                - articleId: 80d221a2-bb24-4f8f-983f-e77db5737a41
                  author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                  createdAt: "2014-08-01T11:05:33Z"
                  description: Ea mollitia facere ut inventore voluptatem.
                  favorited: true
                  favoritesCount: 14126625635488546158
                  tagList:
                    - Perferendis quo pariatur nulla velit doloribus.
                    - Ullam autem libero molestiae error.
                  title: Voluptas optio quia sint sequi ut.
                  updatedAt: "1976-02-29T20:46:09Z"
        required:
            - articles
    ArticleSummary:
        title: ArticleSummary
        type: object
        properties:
            articleId:
                type: string
                example: 9dc4dec5-cf32-48b6-b0c9-a2e8290bccbd
                format: uuid
            author:
                $ref: '#/definitions/Profile'
            createdAt:
                type: string
                example: "1991-09-26T17:05:12Z"
                format: date-time
            description:
                type: string
                example: Error consequatur nisi.
            favorited:
                type: boolean
                example: false
            favoritesCount:
                type: integer
                example: 10125828801107059748
                format: int64
            tagList:
                type: array
                items:
                    type: string
                    example: Sapiente eum ipsam ut omnis voluptatem in.
                example:
                    - Dolorem quasi incidunt enim.
                    - Accusamus minus tenetur facilis dicta.
            title:
                type: string
                example: Et quasi nemo voluptatem.
            updatedAt:
                type: string
                example: "1978-12-14T03:32:32Z"
                format: date-time
        example:
            articleId: 8f9e7bdc-5dad-4ec7-b33e-5a6ce4dafa18
            author:
                bio: Quas architecto voluptas.
                following: true
                image: Reiciendis ab voluptas adipisci non.
                username: Nostrum voluptate minima incidunt hic quis.
            createdAt: "1987-02-12T20:14:31Z"
            description: Dolorem et est cum.
            favorited: true
            favoritesCount: 15962651114805472077
            tagList:
                - Excepturi est enim.
                - Alias consequatur.
                - Veniam est dolores reprehenderit.
            title: Ut commodi dolores quos.
            updatedAt: "2012-03-22T11:16:10Z"
        required:
            - articleId
            - title
            - description
            - tagList
            - createdAt
            - updatedAt
            - favorited
            - favoritesCount
            - author
    ArticleUnfavoriteArticleBadRequest:
        title: ArticleUnfavoriteArticleBadRequest
        type: object
        properties:
            code:
                type: string
                example: Unspecified
                enum:
                    - Unspecified
                    - ArticleNotFound
        example:
            code: Unspecified
        required:
            - code
    ArticleUnfavoriteResponseBody:
        title: ArticleUnfavoriteResponseBody
        type: object
        properties:
            article:
                $ref: '#/definitions/ArticleDetail'
        example:
            article:
                articleId: 702ce4ba-5930-428e-b06c-f0ac6b249188
                author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                body: Provident iste eum.
                createdAt: "2000-03-03T11:42:32Z"
                description: Occaecati quas quis excepturi.
                favorited: false
                favoritesCount: 16396543013077051002
                tagList:
                    - Ea provident voluptates laborum hic laborum error.
                    - Iure optio omnis et autem.
                    - Harum et neque minus eveniet vero.
                    - Tenetur dolorum quos sunt aut.
                title: Excepturi possimus molestiae laudantium libero veniam voluptatem.
                updatedAt: "2002-02-05T08:11:46Z"
        required:
            - article
    ArticleUpdateArticleBadRequest:
        title: ArticleUpdateArticleBadRequest
        type: object
        properties:
            code:
                type: string
                example: ForbiddenOperation
                enum:
                    - Unspecified
                    - ArticleNotFound
                    - ForbiddenOperation
        example:
            code: ForbiddenOperation
        required:
            - code
    ArticleUpdateRequestBody:
        title: ArticleUpdateRequestBody
        type: object
        properties:
            body:
                type: string
                example: Aliquid ut corporis odit repellat.
            description:
                type: string
                example: Non autem architecto velit in ab.
            title:
                type: string
                example: ak4
                maxLength: 128
        example:
            body: Et autem culpa.
            description: Et aliquid ea.
            title: a52
    ArticleUpdateResponseBody:
        title: ArticleUpdateResponseBody
        type: object
        properties:
            article:
                $ref: '#/definitions/ArticleDetail'
        example:
            article:
                articleId: 702ce4ba-5930-428e-b06c-f0ac6b249188
                author:
                    bio: Quas architecto voluptas.
                    following: true
                    image: Reiciendis ab voluptas adipisci non.
                    username: Nostrum voluptate minima incidunt hic quis.
                body: Provident iste eum.
                createdAt: "2000-03-03T11:42:32Z"
                description: Occaecati quas quis excepturi.
                favorited: false
                favoritesCount: 16396543013077051002
                tagList:
                    - Ea provident voluptates laborum hic laborum error.
                    - Iure optio omnis et autem.
                    - Harum et neque minus eveniet vero.
                    - Tenetur dolorum quos sunt aut.
                title: Excepturi possimus molestiae laudantium libero veniam voluptatem.
                updatedAt: "2002-02-05T08:11:46Z"
        required:
            - article
    Profile:
        title: Profile
        type: object
        properties:
            bio:
                type: string
                example: Dolores enim ullam.
            following:
                type: boolean
                example: false
            image:
                type: string
                example: Sit et quidem excepturi rerum.
            username:
                type: string
                example: Tenetur repellat minus sint consequatur incidunt ut.
        example:
            bio: Deleniti quis inventore provident et sed.
            following: true
            image: Eum consequatur alias corporis voluptas.
            username: Adipisci et officiis.
        required:
            - username
            - bio
            - image
            - following
    ProfileFollowUserBadRequest:
        title: ProfileFollowUserBadRequest
        type: object
        properties:
            code:
                type: string
                example: CannotFollowYourself
                enum:
                    - Unspecified
                    - UserNotFound
                    - UserAlreadyFollowing
                    - CannotFollowYourself
        example:
            code: UserNotFound
        required:
            - code
    ProfileFollowUserRequestBody:
        title: ProfileFollowUserRequestBody
        type: object
        properties:
            username:
                type: string
                example: ZIIJpjf
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            username: Us4n
        required:
            - username
    ProfileFollowUserResponseBody:
        title: ProfileFollowUserResponseBody
        type: object
        properties:
            profile:
                $ref: '#/definitions/Profile'
        example:
            profile:
                bio: Quas architecto voluptas.
                following: true
                image: Reiciendis ab voluptas adipisci non.
                username: Nostrum voluptate minima incidunt hic quis.
        required:
            - profile
    ProfileUnfollowUserBadRequest:
        title: ProfileUnfollowUserBadRequest
        type: object
        properties:
            code:
                type: string
                example: UserNotFound
                enum:
                    - Unspecified
                    - UserNotFound
                    - UserNotFollowing
        example:
            code: UserNotFound
        required:
            - code
    ProfileUnfollowUserRequestBody:
        title: ProfileUnfollowUserRequestBody
        type: object
        properties:
            username:
                type: string
                example: Nben
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            username: o7bX
        required:
            - username
    ProfileUnfollowUserResponseBody:
        title: ProfileUnfollowUserResponseBody
        type: object
        properties:
            profile:
                $ref: '#/definitions/Profile'
        example:
            profile:
                bio: Quas architecto voluptas.
                following: true
                image: Reiciendis ab voluptas adipisci non.
                username: Nostrum voluptate minima incidunt hic quis.
        required:
            - profile
    User:
        title: User
        type: object
        properties:
            bio:
                type: string
                example: Modi ut quidem dignissimos dolorum velit et.
            email:
                type: string
                example: Quod inventore nam sit velit ratione.
            image:
                type: string
                example: Hic nobis.
            token:
                type: string
                example: Aperiam consectetur veniam quos.
            username:
                type: string
                example: Aut quam.
        example:
            bio: Quia ducimus atque assumenda.
            email: Voluptatem voluptas laboriosam.
            image: Est rerum nobis id ut voluptates.
            token: Omnis est.
            username: Voluptas rerum.
        required:
            - email
            - token
            - username
            - bio
            - image
    UserGetCurrentResponseBody:
        title: UserGetCurrentResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Excepturi adipisci.
                email: Fugiat nostrum quis culpa.
                image: Ut qui.
                token: Sed quis.
                username: Laudantium iste.
        required:
            - user
    UserLoginBadRequest:
        title: UserLoginBadRequest
        type: object
        properties:
            code:
                type: string
                example: PasswordIsIncorrect
                enum:
                    - Unspecified
                    - EmailNotFound
                    - PasswordIsIncorrect
        example:
            code: PasswordIsIncorrect
        required:
            - code
    UserLoginRequestBody:
        title: UserLoginRequestBody
        type: object
        properties:
            email:
                type: string
                example: adolphus@kreigermueller.com
                format: email
            password:
                type: string
                example: iqr
                minLength: 6
                maxLength: 128
        example:
            email: luther.zulauf@murraydickens.name
            password: 9mr
        required:
            - email
            - password
    UserLoginResponseBody:
        title: UserLoginResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Excepturi adipisci.
                email: Fugiat nostrum quis culpa.
                image: Ut qui.
                token: Sed quis.
                username: Laudantium iste.
        required:
            - user
    UserRegisterBadRequest:
        title: UserRegisterBadRequest
        type: object
        properties:
            code:
                type: string
                example: EmailAlreadyUsed
                enum:
                    - Unspecified
                    - UsernameAlreadyUsed
                    - EmailAlreadyUsed
        example:
            code: Unspecified
        required:
            - code
    UserRegisterRequestBody:
        title: UserRegisterRequestBody
        type: object
        properties:
            email:
                type: string
                example: karli_mclaughlin@halvorsonlittle.biz
                format: email
            password:
                type: string
                example: 4cj
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: Xeh
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            email: gabrielle@rippinjast.net
            password: qpd
            username: MFPO
        required:
            - username
            - email
            - password
    UserRegisterResponseBody:
        title: UserRegisterResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Excepturi adipisci.
                email: Fugiat nostrum quis culpa.
                image: Ut qui.
                token: Sed quis.
                username: Laudantium iste.
        required:
            - user
    UserUpdateRequestBody:
        title: UserUpdateRequestBody
        type: object
        properties:
            bio:
                type: string
                example: euk
                maxLength: 4096
            email:
                type: string
                example: janice@dibbert.biz
                format: email
            image:
                type: string
                example: https://zm
                pattern: ^https?://.+$
            password:
                type: string
                example: kl9
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: 85N
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            bio: gcq
            email: reinhold@lehner.org
            image: https://uh
            password: 6b9
            username: 6lHgT3
    UserUpdateResponseBody:
        title: UserUpdateResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Excepturi adipisci.
                email: Fugiat nostrum quis culpa.
                image: Ut qui.
                token: Sed quis.
                username: Laudantium iste.
        required:
            - user
