openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/article/{articleId}:
        get:
            tags:
                - article
            summary: get article
            operationId: article#get
            parameters:
                - name: articleId
                  in: path
                  required: true
                  schema:
                    type: string
                    example: 4836089a-2222-4bda-b79e-4cd7fb7a2fe2
                    format: uuid
                  example: 09d44871-fb08-4b21-a673-6c0a30603b3d
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponseBody'
                            example:
                                article:
                                    articleId: e87538e6-1933-4d16-8e19-135eb87bfffb
                                    author:
                                        bio: Itaque odit ex velit nihil aliquid.
                                        following: true
                                        image: Adipisci magnam placeat.
                                        username: Officiis tempore quia illo.
                                    body: Quas officiis ducimus et.
                                    createdAt: "2003-02-27T13:43:41Z"
                                    description: Animi beatae accusamus et ut autem.
                                    favorited: true
                                    favoritesCount: 7305528292700064403
                                    tagList:
                                        - Qui nostrum dolorum dicta voluptatem.
                                        - Sint et doloremque eligendi.
                                        - Excepturi nisi rem est.
                                    title: Incidunt laudantium ratione.
                                    updatedAt: "2006-07-26T10:45:21Z"
                "400":
                    description: 'ArticleGetArticleBadRequest: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArticleGetArticleBadRequest'
                            example:
                                code: Unspecified
    /api/article/{articleId}/favorite:
        post:
            tags:
                - article
            summary: favorite article
            operationId: article#favorite
            parameters:
                - name: articleId
                  in: path
                  required: true
                  schema:
                    type: string
                    example: 423c8321-1184-45ba-8a61-f5e7233aba0c
                    format: uuid
                  example: c6b5cd7a-8af6-49d8-982c-a370822a5bd2
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponseBody'
                            example:
                                article:
                                    articleId: e87538e6-1933-4d16-8e19-135eb87bfffb
                                    author:
                                        bio: Itaque odit ex velit nihil aliquid.
                                        following: true
                                        image: Adipisci magnam placeat.
                                        username: Officiis tempore quia illo.
                                    body: Quas officiis ducimus et.
                                    createdAt: "2003-02-27T13:43:41Z"
                                    description: Animi beatae accusamus et ut autem.
                                    favorited: true
                                    favoritesCount: 7305528292700064403
                                    tagList:
                                        - Qui nostrum dolorum dicta voluptatem.
                                        - Sint et doloremque eligendi.
                                        - Excepturi nisi rem est.
                                    title: Incidunt laudantium ratione.
                                    updatedAt: "2006-07-26T10:45:21Z"
                "400":
                    description: 'ArticleFavoriteArticleBadRequest: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArticleFavoriteArticleBadRequest'
                            example:
                                code: Unspecified
    /api/article/{articleId}/unfavorite:
        post:
            tags:
                - article
            summary: unfavorite article
            operationId: article#unfavorite
            parameters:
                - name: articleId
                  in: path
                  required: true
                  schema:
                    type: string
                    example: b6bce345-cb10-427a-8cb7-2978155f7d48
                    format: uuid
                  example: 8ca52cd6-cefa-42b7-a7e5-7943f203652a
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponseBody'
                            example:
                                article:
                                    articleId: e87538e6-1933-4d16-8e19-135eb87bfffb
                                    author:
                                        bio: Itaque odit ex velit nihil aliquid.
                                        following: true
                                        image: Adipisci magnam placeat.
                                        username: Officiis tempore quia illo.
                                    body: Quas officiis ducimus et.
                                    createdAt: "2003-02-27T13:43:41Z"
                                    description: Animi beatae accusamus et ut autem.
                                    favorited: true
                                    favoritesCount: 7305528292700064403
                                    tagList:
                                        - Qui nostrum dolorum dicta voluptatem.
                                        - Sint et doloremque eligendi.
                                        - Excepturi nisi rem est.
                                    title: Incidunt laudantium ratione.
                                    updatedAt: "2006-07-26T10:45:21Z"
                "400":
                    description: 'ArticleUnfavoriteArticleBadRequest: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArticleUnfavoriteArticleBadRequest'
                            example:
                                code: Unspecified
    /api/article/create:
        post:
            tags:
                - article
            summary: create article
            operationId: article#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            body: Quis sunt consequuntur.
                            description: Quod repellat beatae.
                            tagList:
                                - Sunt et debitis et facere.
                                - Recusandae ab distinctio qui ratione earum.
                                - Nihil ab ipsa autem dolore nisi aut.
                            title: 9f3
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponseBody'
                            example:
                                article:
                                    articleId: e87538e6-1933-4d16-8e19-135eb87bfffb
                                    author:
                                        bio: Itaque odit ex velit nihil aliquid.
                                        following: true
                                        image: Adipisci magnam placeat.
                                        username: Officiis tempore quia illo.
                                    body: Quas officiis ducimus et.
                                    createdAt: "2003-02-27T13:43:41Z"
                                    description: Animi beatae accusamus et ut autem.
                                    favorited: true
                                    favoritesCount: 7305528292700064403
                                    tagList:
                                        - Qui nostrum dolorum dicta voluptatem.
                                        - Sint et doloremque eligendi.
                                        - Excepturi nisi rem est.
                                    title: Incidunt laudantium ratione.
                                    updatedAt: "2006-07-26T10:45:21Z"
    /api/profile/follow_user:
        post:
            tags:
                - profile
            summary: followUser profile
            operationId: profile#followUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowUserRequestBody'
                        example:
                            username: 5Bh
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FollowUserResponseBody'
                            example:
                                profile:
                                    bio: Itaque odit ex velit nihil aliquid.
                                    following: true
                                    image: Adipisci magnam placeat.
                                    username: Officiis tempore quia illo.
                "400":
                    description: 'ProfileFollowUserBadRequest: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileFollowUserBadRequest'
                            example:
                                code: CannotFollowYourself
    /api/profile/unfollow_user:
        post:
            tags:
                - profile
            summary: unfollowUser profile
            operationId: profile#unfollowUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowUserRequestBody'
                        example:
                            username: E3Yf
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FollowUserResponseBody'
                            example:
                                profile:
                                    bio: Itaque odit ex velit nihil aliquid.
                                    following: true
                                    image: Adipisci magnam placeat.
                                    username: Officiis tempore quia illo.
                "400":
                    description: 'ProfileUnfollowUserBadRequest: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ProfileUnfollowUserBadRequest'
                            example:
                                code: UserNotFollowing
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrent user
            operationId: user#getCurrent
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Reiciendis ab voluptas adipisci non.
                                    email: Qui nostrum voluptate.
                                    image: Repellat et ut aut.
                                    token: Incidunt hic.
                                    username: Odio quas architecto voluptas.
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: lorenza_haley@conn.org
                            password: v4p
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Reiciendis ab voluptas adipisci non.
                                    email: Qui nostrum voluptate.
                                    image: Repellat et ut aut.
                                    token: Incidunt hic.
                                    username: Odio quas architecto voluptas.
                "400":
                    description: 'UserLoginBadRequest: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserLoginBadRequest'
                            example:
                                code: EmailNotFound
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            email: lillian@muller.com
                            password: pfn
                            username: cMUk
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Reiciendis ab voluptas adipisci non.
                                    email: Qui nostrum voluptate.
                                    image: Repellat et ut aut.
                                    token: Incidunt hic.
                                    username: Odio quas architecto voluptas.
                "400":
                    description: 'UserRegisterBadRequest: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserRegisterBadRequest'
                            example:
                                code: EmailAlreadyUsed
    /api/user/update:
        post:
            tags:
                - user
            summary: update user
            operationId: user#update
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            bio: j2r
                            email: zoey_corwin@deckow.net
                            image: http://u
                            password: ssu
                            username: von
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Reiciendis ab voluptas adipisci non.
                                    email: Qui nostrum voluptate.
                                    image: Repellat et ut aut.
                                    token: Incidunt hic.
                                    username: Odio quas architecto voluptas.
components:
    schemas:
        ArticleDetail:
            type: object
            properties:
                articleId:
                    type: string
                    example: b2dbd2c4-18e4-46fb-b7c7-f5d9e4eaa694
                    format: uuid
                author:
                    $ref: '#/components/schemas/Profile'
                body:
                    type: string
                    example: Ipsam omnis qui reiciendis.
                createdAt:
                    type: string
                    example: "1994-02-08T20:08:04Z"
                    format: date-time
                description:
                    type: string
                    example: Sunt minima nostrum.
                favorited:
                    type: boolean
                    example: true
                favoritesCount:
                    type: integer
                    example: 10903506639842704058
                    format: int64
                tagList:
                    type: array
                    items:
                        type: string
                        example: Sequi id consequuntur.
                    example:
                        - Sint consequuntur ab iusto dicta.
                        - Eius veritatis fugiat voluptatem.
                        - Consequatur vitae quis minus.
                        - Incidunt rerum et neque expedita sint.
                title:
                    type: string
                    example: Voluptatem iusto enim.
                updatedAt:
                    type: string
                    example: "2005-09-01T05:01:05Z"
                    format: date-time
            example:
                articleId: b0f34c40-c636-4a30-be61-be032d6a0fab
                author:
                    bio: Rerum quia voluptate minus eum nisi.
                    following: false
                    image: Aut labore.
                    username: Nesciunt quasi totam.
                body: At omnis illo tempore at eum.
                createdAt: "1989-01-07T02:25:35Z"
                description: Omnis suscipit voluptas.
                favorited: true
                favoritesCount: 4208872728665820525
                tagList:
                    - Assumenda dolore voluptatem voluptatem sunt et ab.
                    - Eaque placeat ex impedit cum eos sequi.
                    - Quasi nemo voluptatem et.
                title: Laudantium dolor rem aut.
                updatedAt: "1997-04-15T23:59:42Z"
            required:
                - articleId
                - title
                - description
                - body
                - tagList
                - createdAt
                - updatedAt
                - favorited
                - favoritesCount
                - author
        ArticleFavoriteArticleBadRequest:
            type: object
            properties:
                code:
                    type: string
                    example: Unspecified
                    enum:
                        - Unspecified
                        - ArticleNotFound
            example:
                code: Unspecified
            required:
                - code
        ArticleGetArticleBadRequest:
            type: object
            properties:
                code:
                    type: string
                    example: ArticleNotFound
                    enum:
                        - Unspecified
                        - ArticleNotFound
            example:
                code: Unspecified
            required:
                - code
        ArticleUnfavoriteArticleBadRequest:
            type: object
            properties:
                code:
                    type: string
                    example: ArticleNotFound
                    enum:
                        - Unspecified
                        - ArticleNotFound
            example:
                code: ArticleNotFound
            required:
                - code
        CreateRequestBody:
            type: object
            properties:
                body:
                    type: string
                    example: Beatae illo incidunt.
                description:
                    type: string
                    example: Vel molestiae accusamus autem commodi quo.
                tagList:
                    type: array
                    items:
                        type: string
                        example: Ut repellat ut commodi.
                    example:
                        - Ut dolorem et est.
                        - Eum porro.
                        - Est enim saepe alias consequatur repellat.
                title:
                    type: string
                    example: evh
                    maxLength: 128
            example:
                body: Tempore quia qui dolorum sint qui adipisci.
                description: Qui adipisci doloremque.
                tagList:
                    - Quo aperiam provident necessitatibus nesciunt est doloribus.
                    - Qui repellat pariatur illum.
                    - Quo qui optio alias sed.
                title: 3kt
            required:
                - title
                - description
                - body
                - tagList
        FollowUserRequestBody:
            type: object
            properties:
                username:
                    type: string
                    example: wZpNHe
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                username: cE85
            required:
                - username
        FollowUserResponseBody:
            type: object
            properties:
                profile:
                    $ref: '#/components/schemas/Profile'
            example:
                profile:
                    bio: Itaque odit ex velit nihil aliquid.
                    following: true
                    image: Adipisci magnam placeat.
                    username: Officiis tempore quia illo.
            required:
                - profile
        GetResponseBody:
            type: object
            properties:
                article:
                    $ref: '#/components/schemas/ArticleDetail'
            example:
                article:
                    articleId: e87538e6-1933-4d16-8e19-135eb87bfffb
                    author:
                        bio: Itaque odit ex velit nihil aliquid.
                        following: true
                        image: Adipisci magnam placeat.
                        username: Officiis tempore quia illo.
                    body: Quas officiis ducimus et.
                    createdAt: "2003-02-27T13:43:41Z"
                    description: Animi beatae accusamus et ut autem.
                    favorited: true
                    favoritesCount: 7305528292700064403
                    tagList:
                        - Qui nostrum dolorum dicta voluptatem.
                        - Sint et doloremque eligendi.
                        - Excepturi nisi rem est.
                    title: Incidunt laudantium ratione.
                    updatedAt: "2006-07-26T10:45:21Z"
            required:
                - article
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: krista.sanford@raynor.info
                    format: email
                password:
                    type: string
                    example: fql
                    minLength: 6
                    maxLength: 128
            example:
                email: fritz.pollich@franecki.name
                password: b5l
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/User'
            example:
                user:
                    bio: Reiciendis ab voluptas adipisci non.
                    email: Qui nostrum voluptate.
                    image: Repellat et ut aut.
                    token: Incidunt hic.
                    username: Odio quas architecto voluptas.
            required:
                - user
        Profile:
            type: object
            properties:
                bio:
                    type: string
                    example: Voluptatibus non.
                following:
                    type: boolean
                    example: true
                image:
                    type: string
                    example: Sed qui mollitia provident.
                username:
                    type: string
                    example: Rerum id rerum officiis est.
            example:
                bio: Nemo molestiae quasi nihil molestias.
                following: true
                image: Esse doloremque numquam sed officia exercitationem odio.
                username: Iure est culpa laboriosam tempora ullam non.
            required:
                - username
                - bio
                - image
                - following
        ProfileFollowUserBadRequest:
            type: object
            properties:
                code:
                    type: string
                    example: UserAlreadyFollowing
                    enum:
                        - Unspecified
                        - UserNotFound
                        - UserAlreadyFollowing
                        - CannotFollowYourself
            example:
                code: Unspecified
            required:
                - code
        ProfileUnfollowUserBadRequest:
            type: object
            properties:
                code:
                    type: string
                    example: UserNotFound
                    enum:
                        - Unspecified
                        - UserNotFound
                        - UserNotFollowing
            example:
                code: Unspecified
            required:
                - code
        RegisterRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: jamison@wyman.biz
                    format: email
                password:
                    type: string
                    example: dkq
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: KZpxz
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                email: milan@murazik.net
                password: pgn
                username: xCDa
            required:
                - username
                - email
                - password
        UpdateRequestBody:
            type: object
            properties:
                bio:
                    type: string
                    example: j7i
                    maxLength: 4096
                email:
                    type: string
                    example: karine.abernathy@kundeshields.name
                    format: email
                image:
                    type: string
                    example: https://5
                    pattern: ^https?://.+$
                password:
                    type: string
                    example: d1p
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: be1N
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                bio: mh2
                email: kiera.armstrong@mcculloughorn.com
                image: https://wj
                password: pnd
                username: fSP
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Est soluta.
                email:
                    type: string
                    example: Omnis adipisci et et voluptas.
                image:
                    type: string
                    example: Dolor cum at vel sint suscipit impedit.
                token:
                    type: string
                    example: Recusandae dolorem repudiandae.
                username:
                    type: string
                    example: Sed facere qui velit nam.
            example:
                bio: Voluptatum est.
                email: Mollitia explicabo perspiciatis fugit ut perspiciatis odit.
                image: Numquam nihil fuga quia assumenda.
                token: Quidem dignissimos dolorum natus.
                username: Dolor et provident sint et velit.
            required:
                - email
                - token
                - username
                - bio
                - image
        UserLoginBadRequest:
            type: object
            properties:
                code:
                    type: string
                    example: EmailNotFound
                    enum:
                        - Unspecified
                        - EmailNotFound
                        - PasswordIsIncorrect
            example:
                code: PasswordIsIncorrect
            required:
                - code
        UserRegisterBadRequest:
            type: object
            properties:
                code:
                    type: string
                    example: EmailAlreadyUsed
                    enum:
                        - Unspecified
                        - UsernameAlreadyUsed
                        - EmailAlreadyUsed
            example:
                code: UsernameAlreadyUsed
            required:
                - code
tags:
    - name: article
      description: article
    - name: profile
      description: profile
    - name: user
      description: user
